### ISSUE TITLE
Bug: Could not parse your model

### ISSUE THREAD

**Issue by carrascomj** [DD-DeCaF/memote-webservice#21]
### Description
Consistently getting _Could not parse your model_ when uploading files to the memote webservice.

### Steps to reproduce
1. Download the model at https://github.com/opencobra/memote/blob/develop/tests/data/EcoliCore.xml.gz
2. Upload `EcoliCore.xml.gz` to [memote.io](https://memote.io/): get _Could not parse your model_ error..
3. Try with unzipped file:
```bash
gunzip EcoliCore.xml.gz
```
4. Upload `EcoliCore.xml` file to [memote.io](https://memote.io/): get _Could not parse your model_

### Browser
Reproducible on (at least) Firefox and Chromium-derived browsers.

**Comment by vh-mol** [comment]
I get the same error, but with the additional _Internal server error_ message.

**Comment by kvikshaug** [comment]
I think this is due to some issue with the latest python dependencies. The internal error message is `AttributeError: module 'werkzeug' has no attribute 'secure_filename'`. That should either be investigated (it might be a simple fix), or the upgrade should be postponed. [This pinned set of requirements](https://github.com/DD-DeCaF/memote-webservice/commit/86d17d66a1358cc9981f17e4eea60b7a28d9cc89) is known to be working, and it looks like [this recent upgrade](https://github.com/DD-DeCaF/memote-webservice/commit/5e494087ac3ca363532558b697d46859cde72fa1) reintroduced the issue.
